module.json

You can 🙈 merge this
stupid little property that I need there or my module won't compile
sorry about making you more work 😓

add system manifest url

---

lang/en.json
module.json
scripts/actions/computers/access-infosphere.mjs
scripts/actions/computers/hack.mjs
scripts/actions/computers/program.mjs
scripts/actions/index.mjs
scripts/actions/piloting/drive.mjs
scripts/actions/piloting/navigate.mjs
scripts/actions/piloting/plot-course.mjs
scripts/actions/piloting/run-over.mjs
scripts/actions/piloting/stop.mjs
scripts/actions/piloting/stunt.mjs
scripts/actions/piloting/take-control.mjs
scripts/sf2e-playtest.mjs

Add SF2E-specific skill actions

---

packs/spells/Analyze_Target_soIbLojIZyKRhyA8.json

Correct description and duration of Analyze Target

---

packs/spells/Pocket_Vacuum_xLAAjxlVce0zFPMs.json

Add heightening to Pocket Vacuum spell

---

packs/classes/Mystic_FunBoU8459ZUpR3O.json

add Weapon Expertise class feature to Mystic Class

---

packs/equipment/Missile_Launcher_mpcNkCf0K3es5uJc.json

also add base range and reload time

Update Missile Launcher action cost

---

packs/conditions/Effect__Vitality_Network_R0mn1iC3nYvDVKhd.json

- Additional text and formula for max total HP for the network.

brush up Vitality Network Effect

---

packs/equipment/Spell_Chip__1st_Rank_Spell__bpU5tJ3dATZfDtoK.json
packs/equipment/Spell_Chip__2nd_Rank_Spell__ikPZaVtxv5w5hFgb.json
packs/equipment/Spell_Chip__3rd_Rank_Spell__bXVe3cvUp3tLR0aJ.json
packs/equipment/Spell_Chip__4th_Rank_Spell__Y2futubYHfImes32.json
packs/equipment/Spell_Chip__5th_Rank_Spell__Yif8kuQ813f6O7Bu.json
packs/equipment/Spell_Chip__6th_Rank_Spell__2fzswZiAtI3qxrPA.json
packs/equipment/Spell_Chip__7th_Rank_Spell__qTLS39SYG1GdIZkH.json
packs/equipment/Spell_Chip__8th_Rank_Spell__JXifR8L1N4PgfTCv.json
packs/equipment/Spell_Chip__9th_Rank_Spell__9iwK4ChWQJYidek2.json

Make spell chips not auto-destroy

---

.gitignore
LICENSE
build.mjs
package-lock.json
package.json

`npm ci` followed by `npm run build`

Add a build script and set license

---

packs/conditions/Effect__Solar_Weapon__Twin__IHp2EZvBMcumn6Hf.json
packs/conditions/Effect__Solar_Weapon_lUZuBzMe0UAllDxX.json

Fix Solar Weapon damage when photon attuned

---

styles/high-contrast.css

Improved readability of versatile damage toggles in high contrast mode

---

styles/high-contrast.css
styles/light.css

Disable whitespace when viewing changes to get the real diff. I also did very minor cleanup on the high contrast theme.

Apply trait style to item and chat for all styles

---

packs/class-features/Envoy_Weapon_Expertise_wes8kS7yjIPrFs1Z.json

Grant proficiency and critical specialization with Envoy Weapon Expertise

---

packs/feats/Get_Down__xI0EGnLqwXJBleTF.json
packs/feats/Warning_Spray_MXahw1PJeKADO223.json

correct action cost for Get Down and Warning Spray feats

---

packs/creatures/Repair_Drone_QaeFn9B6sgpkuh2g.json

Reported by [Mr. Fred](https://gitlab.metamorphic-digital.com/sigil-services/fvtt/paizo/sa/sf2e-playtest-deluxe-adventure-pack/-/issues/67)

Add mental immunity to Repair Drone (Playtest Scenario #1)

---

lang/en.json
module.json
packs/equipment/Shotalashu_Armor_TjqRzpHBljeq1c7k.json

Update Shotalashu Armor localization

---

packs/equipment/Grenade_Launcher_LyLkKttGATjo4wIs.json

Grenade Launcher is Bulk 3, considered a martial weapon, and has a reload of 2 (even though yeah, it's not going to actually be fired in the system since I don't think Grenades are ammo).

Fix Grenade Launcher

---

packs/actions/Stunt_ailFBRjKuGCOAsCR.json

Update action cost of Stunt

---

lang/en.json
module.json
packs/creatures/Ad_Twist_sM1DVAhBoiaFFHxn.json
packs/creatures/Armed_Defrex_j4WT4V8Gd7H2Dp1S.json
packs/creatures/Comet_Wasp_Swarm_EDVwFaOOPrFHkS0w.json
packs/creatures/Corpse_Fleet_Screamer_xOKiJjIUQhQoHuie.json
packs/creatures/Corpse_Fleet_Sniper_6wOvXBkAugqTgqjb.json
packs/creatures/Cybernetic_Shuln_Y0srihG1KJ8NJUlo.json
packs/creatures/Famesworn_tZjTQq1loACCJlPU.json
packs/creatures/Fiendish_Ellicoth_YhMCPYOIovhJY4bS.json
packs/creatures/Shocking_Twist_zdIvCVbPO5vLq1bW.json
packs/creatures/Stridermander_Tyrant_41OoB4HzN5au1wye.json
packs/creatures/Swarm_Dissolver_ACnRD5xcMACTD6Ti.json
packs/creatures/Troll_Bombard_yBmfHisqQg3iZEpe.json
packs/creatures/Void_Shark_xHtoDBTBuK9HgZdt.json
packs/creatures/Zo_ceratops_0bczK10rh07QaQn1.json
packs/feats/Brutal_Anatomy_64hqNZ7cAdUMKEJK.json

Also fixes several open issues
Closes #130
Closes #129 
Closes #125

Add content from Wheel of Monsters

---

module.json

Lashuntas speak "Castrovelian"

Remove "Lashunta" language

---

packs/spells/Implant_Data_BmCv54hcNK6rA4q1.json

Add action cost to Implant Data spell

---

packs/equipment/Ballistic_Missile__Advanced__poOc123C2PVzHDdj.json
packs/equipment/Ballistic_Missile__Commercial__VQiQ9yMgAZ100bo2.json
packs/equipment/Ballistic_Missile__Elite__fNPOs4QpOVwco2X7.json
packs/equipment/Ballistic_Missile__Paragon__wdITOphUNb3zUcuB.json
packs/equipment/Ballistic_Missile__Superior__X06ZVZShnzXzWwrI.json
packs/equipment/Ballistic_Missile__Tactical__uBWiuVIBpdqkcbOF.json
packs/equipment/Ballistic_Missile__Ultimate__kddNd39P0s7CQzr4.json

It's a splash damage, so no reflex save.

Fix Ballistic Missile damage, splash radius, and price

---

packs/equipment/Doshko_jnvg0NRqshhK1uND.json

Remove `unwieldy` trait from Doshko

---

packs/equipment/Frag_Grenade__Commercial__P1ZlvQaS76dFhs93.json

Correct level on Commercial Frag Grenade

---

packs/equipment/Incendiary_Grenade__Advanced__DutOVpDTG4BPTeAD.json
packs/equipment/Incendiary_Grenade__Commercial__OL5KQFxrMrSm3us0.json
packs/equipment/Incendiary_Grenade__Elite__kLElo57JSgmMstY4.json
packs/equipment/Incendiary_Grenade__Paragon__BdiWrdKxofluw8VO.json
packs/equipment/Incendiary_Grenade__Superior__Aj4TtlwVRqhUMaFe.json
packs/equipment/Incendiary_Grenade__Tactical__DVOS7Two8quNMywp.json
packs/equipment/Incendiary_Grenade__Ultimate__pb4cxfAe7wAjibIE.json

Add inline burst template to Incendiary Grenade variants

---

packs/equipment/Flash_Grenade__Advanced__dRFE2KicnIpLAO91.json
packs/equipment/Flash_Grenade__Commercial__CaKo7m7RQUJxE2Mu.json
packs/equipment/Flash_Grenade__Elite__iyEvSil33AkVeg2m.json
packs/equipment/Flash_Grenade__Paragon__Q2Tp75mVieeQBeCJ.json
packs/equipment/Flash_Grenade__Superior__jfWbt1GLwgEHtXd5.json
packs/equipment/Flash_Grenade__Tactical__nr72tK0MALusfqky.json
packs/equipment/Flash_Grenade__Ultimate__4ZfMlHQrx56qrCC5.json
packs/equipment/Smoke_Grenade__Advanced__2PWtSXC9bUvt5XYk.json
packs/equipment/Smoke_Grenade__Commercial__kifk9JICS5ZrBhSs.json
packs/equipment/Smoke_Grenade__Elite__bLjXv5w0TF0yj2lA.json
packs/equipment/Smoke_Grenade__Paragon__eL4bwTtmgNiknE5R.json
packs/equipment/Smoke_Grenade__Superior__a3mvpddR38bEzx9G.json
packs/equipment/Smoke_Grenade__Tactical__F7d8M5WI4FgKDDHJ.json
packs/equipment/Smoke_Grenade__Ultimate__UnJPm0f69hvepJAT.json

Add link to Area Fire action to Flash Grenade and Smoke Grenade (and their corresponding variants)

---

packs/equipment/Seeker_Rifle_iVXp5YJmxysaYSJz.json

Update Seeker Rifle per latest SF2e errata

---

packs/equipment/Animated_Intelligence__Commercial__WTuFICi2wyQ6KnkB.json
packs/equipment/Animated_Intelligence__Tactical__6XsmZE68rKZ1Sk4h.json
packs/equipment/Entropic_Destabilizer__Commercial__Ha2KajipLLsNKe7Q.json
packs/equipment/Entropic_Destabilizer__Tactical__O5fv3sxASsLhZcqe.json
packs/equipment/Fear_Projector__Commercial__YcqFOXbBPbRSxG0x.json
packs/equipment/Fear_Projector__Tactical__LjzVHOoJXUQovw3B.json
packs/equipment/Flaming_Module__Commercial__TDKfnoxIWEH5sbOK.json
packs/equipment/Flaming_Module__Tactical__yMZsoPIPqnaocE3p.json
packs/equipment/Frost_Module__Commercial__zeJ3c8JYJygFcMss.json
packs/equipment/Frost_Module__Tactical__2Ul7gp5upCjgjiHG.json
packs/equipment/Loudener__Commercial__zc7Kh2psza1YAcgy.json
packs/equipment/Loudener__Tactical__GekkQLU6Jl0boPb2.json
packs/equipment/Shock_Module__Commercial__Vyid3kqvnFB1KTet.json
packs/equipment/Shock_Module__Tactical__vLEzcjsBMCtm3J2Y.json
packs/equipment/Smuggler_s_Grip__Commercial__O0cuj6CI1GzAVPke.json
packs/equipment/Smuggler_s_Grip__Tactical__GBZl7M6Kk1fns025.json
packs/equipment/Sniper_s_Scope__Advanced__BYeLX8iq2AOqAV4T.json
packs/equipment/Sniper_s_Scope__Commercial__M9vZjxXVI5hC2eRK.json
packs/equipment/Sniper_s_Scope__Superior__Mx9VkkmrmtM30wyu.json
packs/equipment/Sniper_s_Scope__Tactical__760PfE4ujWc06muX.json
packs/equipment/Truesight_Sight__Commercial__XF5ojfhO90XKUuEF.json
packs/equipment/Truesight_Sight__Tactical__2ics9FlhNjVpBNtT.json
packs/equipment/Undermounted_Grenade_Launcher__Advanced__MK20SbPEbHYWNVxP.json
packs/equipment/Undermounted_Grenade_Launcher__Commercial__F3eZ72QLXl2RnvOD.json
packs/equipment/Undermounted_Grenade_Launcher__Superior__XL5r9MRYzsd7dK1n.json
packs/equipment/Undermounted_Grenade_Launcher__Tactical__XVAdFpirzWZONGTi.json

Add variants to select weapon upgrades

---

packs/class-features/Walking_Armory_Uvr1IK2HthLtN5wC.json

Thanks @pedrogrullada for the assist!
Closes #17

Automate Soldier's Walking Armory armor penalties accounting for Constitution modifier

---

packs/feats/Predatory_fxvB97t697mMFUJs.json

Fixing issue https://github.com/TikaelSol/starfinder-field-test/issues/171

Fix Pahtra Predatory Ancestry Feat label

---

packs/feats/Armor_Ace_MTKq34DpjCtmIqxe.json

Closes #175
Well, in one aspect

Update Armor Ace adjust modifier to target reflex instead of AC

---

lang/en.json
packs/actions/Attune_JLo2gJ2s0BXUKsLQ.json
packs/conditions/Effect__Solar_Shield_q5W7fV1wXvqBFxt8.json
packs/feats/Solar_Shield_ZPj5TjISL153EGpW.json

Add automation and effect to Solarian Solar Shield feat

---

packs/creatures/Heliacal_Maw_Ferocitum_Knb8oNA0MAV2kxOt.json

Correct Heliacal Maw Ferocitum's Hit Point

---

packs/conditions/Spell_Effect__Skyfire_Wings_2O63RRDOEQlGL2BS.json
packs/conditions/Spell_Effect__Skyfire_Wings__1_Hour__oYOt7f1cyXs3jj8P.json
packs/conditions/Spell_Effect__Skyfire_Wings__5_Minutes__9wtEBwpUhvRdnqJz.json
packs/conditions/Spell_Effect__Skyfire_Wings__8_Hours__Oc7rfrPBpjKhcYXc.json
packs/spells/Skyfire_Wings_rgIXThpMnowIYvol.json

Add spell effects for Skyfire Wings and add missing traits

---

packs/actions/Aim_LRbwV8LMLi6FFKjW.json
packs/class-features/Striker_OBUIFNBSHc2EfDER.json
packs/conditions/Effect__Aim_9grXj8ftRJnXpyxW.json

Implement Striker Operative's Aim damage

---

packs/conditions/Effect__Brace_For_Impact_JaysqWTGfMgvx93E.json
packs/conditions/Effect__Cloud_Storage_3bbBxY9CtdW0aBpE.json
packs/conditions/Effect__Confounding_Disquisition_KEZy8RB16MleX5NY.json
packs/conditions/Effect__Vitality_Network_R0mn1iC3nYvDVKhd.json
packs/conditions/Spell_Effect__Wild_Bond_aFR3wmqJ83sccJ1p.json
packs/feats/Cloud_Storage_ETSpdE13hb3RDmYM.json
packs/feats/Combine_mPubmQ2KAWqgXKWm.json
packs/feats/Corrosive_Venting_rWpDNMJtAKhqQfXt.json
packs/feats/Encode_Presence_yE5x8G7C74gTOgLX.json
packs/feats/Internal_Chemistry_lgb3IeqIo1b3xa8M.json
packs/feats/Perfectly_Balanced_yO9F5PBGRYvrhn37.json
packs/feats/Psychic_Investigator_COrch31T2tZ3yUtR.json
packs/feats/Undying_mV0sqFwQSoNp0ryK.json
packs/feats/Verbal_Transmission_TPjUonmchJqBzlSa.json
packs/spells/Glow_Up_5Rlci7rhYnFRHGt8.json
packs/spells/Scan_Environment_cAmT1koSUoQHSYs1.json

Implement corrections for issues pointed out in #188

---

packs/feats/Get_in_There__9TeJIbN2nv8DRJ0x.json

Correct typo in `Get in there!` feat

---

lang/en.json
packs/conditions/Effect__Force_Field_WAXL7euS0jMn5oWi.json
packs/equipment/Force_Field__Advanced__NDPfev2xcINGpxv4.json
packs/equipment/Force_Field__Commercial__iUq9gG7jSnm4oCD2.json
packs/equipment/Force_Field__Elite__l91L8dHQT2ddmufW.json
packs/equipment/Force_Field__Paragon__Ze53S8GhMbHexvGF.json
packs/equipment/Force_Field__Superior__8yEnhqeRKBxO02M2.json
packs/equipment/Force_Field__Tactical__WgLegYXfJWtPOB3m.json
packs/equipment/Force_Field__Ultimate__Hqxyg3xDDoqYLNO3.json

Add effect for forcefield

---

build.mjs
lang/en.json
scripts/actions/area-fire.mjs
scripts/sf2e-playtest.mjs
templates/area-fire-message.hbs

Works via aux buttons. No support for grenades or grenade launchers. I'm not sure what to do about critical specialization, but I'm considering always showing the crit spec in the damage just in case since it applies to an entire area.

Add automation for area and auto fire

---

scripts/actions/area-fire.mjs

Closes https://github.com/TikaelSol/starfinder-field-test/issues/236

Set range of auto fire cone to half instead of full

---

packs/equipment/Cloaking_Skin__Advanced__NhJQJWTci9RwjpS4.json
packs/equipment/Cloaking_Skin__Commercial__6c8AMkud3SHUzpHY.json
packs/equipment/Cloaking_Skin__Tactical__IL68IiUgSkFdmWTv.json

From the original SF2e Playtest book, a missed item

Add Cloaking Skin augmentation

---

packs/heritages/Shipborn_Dragonkin_qRHZENQf5C43t3q4.json

Set size to medium for Shipborn Dragonkin Closes: #262

---

link.mjs
styles/dark.css
styles/high-contrast.css
styles/light.css

Depends on https://github.com/foundryvtt/pf2e/pull/19514
This fixes some of the regressions on the sheets, fixes encumbrance colors, and starts the process towards reducing the number of overrides on the light sheet (outside of colors, which are meant to be overriden). It also replaces the green with the primary color

Minor fixes and tweaks to all 3 sheets

---

packs/equipment/Turret_Weapon_88rxNOd1iuR9IR9o.json

Make turret weapon simpler to use
